package com.zyy.taskmanage.dao.model;

import java.io.Serializable;

public class DeviceExternal implements Serializable {
    /**
     * 集中器扩展表
     * 表字段 : device_external.id
     */
    private Long id;

    /**
     * 通讯号
     * 表字段 : device_external.channel_no
     */
    private String channelNo;

    /**
     * 变更状态：0：无，1：有
     * 表字段 : device_external.change_status
     */
    private Byte changeStatus;

    /**
     * 同步状态：0：同步中，1：同步结束
     * 表字段 : device_external.sync_status
     */
    private Byte syncStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table device_external
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取：集中器扩展表
     * 表字段：device_external.id
     *
     * @return device_external.id：集中器扩展表
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置：集中器扩展表
     * 表字段：device_external.id
     *
     * @param id
     *            device_external.id：集中器扩展表
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取：通讯号
     * 表字段：device_external.channel_no
     *
     * @return device_external.channel_no：通讯号
     */
    public String getChannelNo() {
        return channelNo;
    }

    /**
     * 设置：通讯号
     * 表字段：device_external.channel_no
     *
     * @param channelNo
     *            device_external.channel_no：通讯号
     */
    public void setChannelNo(String channelNo) {
        this.channelNo = channelNo == null ? null : channelNo.trim();
    }

    /**
     * 获取：变更状态：0：无，1：有
     * 表字段：device_external.change_status
     *
     * @return device_external.change_status：变更状态：0：无，1：有
     */
    public Byte getChangeStatus() {
        return changeStatus;
    }

    /**
     * 设置：变更状态：0：无，1：有
     * 表字段：device_external.change_status
     *
     * @param changeStatus
     *            device_external.change_status：变更状态：0：无，1：有
     */
    public void setChangeStatus(Byte changeStatus) {
        this.changeStatus = changeStatus;
    }

    /**
     * 获取：同步状态：0：同步中，1：同步结束
     * 表字段：device_external.sync_status
     *
     * @return device_external.sync_status：同步状态：0：同步中，1：同步结束
     */
    public Byte getSyncStatus() {
        return syncStatus;
    }

    /**
     * 设置：同步状态：0：同步中，1：同步结束
     * 表字段：device_external.sync_status
     *
     * @param syncStatus
     *            device_external.sync_status：同步状态：0：同步中，1：同步结束
     */
    public void setSyncStatus(Byte syncStatus) {
        this.syncStatus = syncStatus;
    }
}