package com.zyy.taskmanage.dao.model;

import java.util.ArrayList;
import java.util.List;

public class DeviceDmxExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table device_dmx
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table device_dmx
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table device_dmx
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     *
     */
    public DeviceDmxExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *
     * @param orderByClause
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *
     * @param distinct
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     *
     * @param criteria
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     *
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * 类注释
     * GeneratedCriteria
     * 数据库表：device_dmx
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOnlineNodeNumIsNull() {
            addCriterion("online_node_num is null");
            return (Criteria) this;
        }

        public Criteria andOnlineNodeNumIsNotNull() {
            addCriterion("online_node_num is not null");
            return (Criteria) this;
        }

        public Criteria andOnlineNodeNumEqualTo(Integer value) {
            addCriterion("online_node_num =", value, "onlineNodeNum");
            return (Criteria) this;
        }

        public Criteria andOnlineNodeNumNotEqualTo(Integer value) {
            addCriterion("online_node_num <>", value, "onlineNodeNum");
            return (Criteria) this;
        }

        public Criteria andOnlineNodeNumGreaterThan(Integer value) {
            addCriterion("online_node_num >", value, "onlineNodeNum");
            return (Criteria) this;
        }

        public Criteria andOnlineNodeNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("online_node_num >=", value, "onlineNodeNum");
            return (Criteria) this;
        }

        public Criteria andOnlineNodeNumLessThan(Integer value) {
            addCriterion("online_node_num <", value, "onlineNodeNum");
            return (Criteria) this;
        }

        public Criteria andOnlineNodeNumLessThanOrEqualTo(Integer value) {
            addCriterion("online_node_num <=", value, "onlineNodeNum");
            return (Criteria) this;
        }

        public Criteria andOnlineNodeNumIn(List<Integer> values) {
            addCriterion("online_node_num in", values, "onlineNodeNum");
            return (Criteria) this;
        }

        public Criteria andOnlineNodeNumNotIn(List<Integer> values) {
            addCriterion("online_node_num not in", values, "onlineNodeNum");
            return (Criteria) this;
        }

        public Criteria andOnlineNodeNumBetween(Integer value1, Integer value2) {
            addCriterion("online_node_num between", value1, value2, "onlineNodeNum");
            return (Criteria) this;
        }

        public Criteria andOnlineNodeNumNotBetween(Integer value1, Integer value2) {
            addCriterion("online_node_num not between", value1, value2, "onlineNodeNum");
            return (Criteria) this;
        }

        public Criteria andControllerNumIsNull() {
            addCriterion("controller_num is null");
            return (Criteria) this;
        }

        public Criteria andControllerNumIsNotNull() {
            addCriterion("controller_num is not null");
            return (Criteria) this;
        }

        public Criteria andControllerNumEqualTo(Integer value) {
            addCriterion("controller_num =", value, "controllerNum");
            return (Criteria) this;
        }

        public Criteria andControllerNumNotEqualTo(Integer value) {
            addCriterion("controller_num <>", value, "controllerNum");
            return (Criteria) this;
        }

        public Criteria andControllerNumGreaterThan(Integer value) {
            addCriterion("controller_num >", value, "controllerNum");
            return (Criteria) this;
        }

        public Criteria andControllerNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("controller_num >=", value, "controllerNum");
            return (Criteria) this;
        }

        public Criteria andControllerNumLessThan(Integer value) {
            addCriterion("controller_num <", value, "controllerNum");
            return (Criteria) this;
        }

        public Criteria andControllerNumLessThanOrEqualTo(Integer value) {
            addCriterion("controller_num <=", value, "controllerNum");
            return (Criteria) this;
        }

        public Criteria andControllerNumIn(List<Integer> values) {
            addCriterion("controller_num in", values, "controllerNum");
            return (Criteria) this;
        }

        public Criteria andControllerNumNotIn(List<Integer> values) {
            addCriterion("controller_num not in", values, "controllerNum");
            return (Criteria) this;
        }

        public Criteria andControllerNumBetween(Integer value1, Integer value2) {
            addCriterion("controller_num between", value1, value2, "controllerNum");
            return (Criteria) this;
        }

        public Criteria andControllerNumNotBetween(Integer value1, Integer value2) {
            addCriterion("controller_num not between", value1, value2, "controllerNum");
            return (Criteria) this;
        }

        public Criteria andProgramConfigIdIsNull() {
            addCriterion("program_config_id is null");
            return (Criteria) this;
        }

        public Criteria andProgramConfigIdIsNotNull() {
            addCriterion("program_config_id is not null");
            return (Criteria) this;
        }

        public Criteria andProgramConfigIdEqualTo(Long value) {
            addCriterion("program_config_id =", value, "programConfigId");
            return (Criteria) this;
        }

        public Criteria andProgramConfigIdNotEqualTo(Long value) {
            addCriterion("program_config_id <>", value, "programConfigId");
            return (Criteria) this;
        }

        public Criteria andProgramConfigIdGreaterThan(Long value) {
            addCriterion("program_config_id >", value, "programConfigId");
            return (Criteria) this;
        }

        public Criteria andProgramConfigIdGreaterThanOrEqualTo(Long value) {
            addCriterion("program_config_id >=", value, "programConfigId");
            return (Criteria) this;
        }

        public Criteria andProgramConfigIdLessThan(Long value) {
            addCriterion("program_config_id <", value, "programConfigId");
            return (Criteria) this;
        }

        public Criteria andProgramConfigIdLessThanOrEqualTo(Long value) {
            addCriterion("program_config_id <=", value, "programConfigId");
            return (Criteria) this;
        }

        public Criteria andProgramConfigIdIn(List<Long> values) {
            addCriterion("program_config_id in", values, "programConfigId");
            return (Criteria) this;
        }

        public Criteria andProgramConfigIdNotIn(List<Long> values) {
            addCriterion("program_config_id not in", values, "programConfigId");
            return (Criteria) this;
        }

        public Criteria andProgramConfigIdBetween(Long value1, Long value2) {
            addCriterion("program_config_id between", value1, value2, "programConfigId");
            return (Criteria) this;
        }

        public Criteria andProgramConfigIdNotBetween(Long value1, Long value2) {
            addCriterion("program_config_id not between", value1, value2, "programConfigId");
            return (Criteria) this;
        }

        public Criteria andWidthIsNull() {
            addCriterion("width is null");
            return (Criteria) this;
        }

        public Criteria andWidthIsNotNull() {
            addCriterion("width is not null");
            return (Criteria) this;
        }

        public Criteria andWidthEqualTo(Integer value) {
            addCriterion("width =", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotEqualTo(Integer value) {
            addCriterion("width <>", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthGreaterThan(Integer value) {
            addCriterion("width >", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthGreaterThanOrEqualTo(Integer value) {
            addCriterion("width >=", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthLessThan(Integer value) {
            addCriterion("width <", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthLessThanOrEqualTo(Integer value) {
            addCriterion("width <=", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthIn(List<Integer> values) {
            addCriterion("width in", values, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotIn(List<Integer> values) {
            addCriterion("width not in", values, "width");
            return (Criteria) this;
        }

        public Criteria andWidthBetween(Integer value1, Integer value2) {
            addCriterion("width between", value1, value2, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotBetween(Integer value1, Integer value2) {
            addCriterion("width not between", value1, value2, "width");
            return (Criteria) this;
        }

        public Criteria andHeightIsNull() {
            addCriterion("height is null");
            return (Criteria) this;
        }

        public Criteria andHeightIsNotNull() {
            addCriterion("height is not null");
            return (Criteria) this;
        }

        public Criteria andHeightEqualTo(Integer value) {
            addCriterion("height =", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotEqualTo(Integer value) {
            addCriterion("height <>", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThan(Integer value) {
            addCriterion("height >", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("height >=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThan(Integer value) {
            addCriterion("height <", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThanOrEqualTo(Integer value) {
            addCriterion("height <=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightIn(List<Integer> values) {
            addCriterion("height in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotIn(List<Integer> values) {
            addCriterion("height not in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightBetween(Integer value1, Integer value2) {
            addCriterion("height between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotBetween(Integer value1, Integer value2) {
            addCriterion("height not between", value1, value2, "height");
            return (Criteria) this;
        }
    }

    /**
     * 类注释
     * Criteria
     * 数据库表：device_dmx
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * 类注释
     * Criterion
     * 数据库表：device_dmx
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}