package com.zyy.taskmanage.dao.model;

import java.io.Serializable;

public class DeviceDmx implements Serializable {
    /**
     * DMX扩展表主键ID
     * 表字段 : device_dmx.id
     */
    private Long id;

    /**
     * 联机数
     * 表字段 : device_dmx.online_node_num
     */
    private Integer onlineNodeNum;

    /**
     * 控制器总数
     * 表字段 : device_dmx.controller_num
     */
    private Integer controllerNum;

    /**
     * 当前播放的节目ID
     * 表字段 : device_dmx.program_config_id
     */
    private Long programConfigId;

    /**
     * 宽度
     * 表字段 : device_dmx.width
     */
    private Integer width;

    /**
     * 高度
     * 表字段 : device_dmx.height
     */
    private Integer height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table device_dmx
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取：DMX扩展表主键ID
     * 表字段：device_dmx.id
     *
     * @return device_dmx.id：DMX扩展表主键ID
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置：DMX扩展表主键ID
     * 表字段：device_dmx.id
     *
     * @param id
     *            device_dmx.id：DMX扩展表主键ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取：联机数
     * 表字段：device_dmx.online_node_num
     *
     * @return device_dmx.online_node_num：联机数
     */
    public Integer getOnlineNodeNum() {
        return onlineNodeNum;
    }

    /**
     * 设置：联机数
     * 表字段：device_dmx.online_node_num
     *
     * @param onlineNodeNum
     *            device_dmx.online_node_num：联机数
     */
    public void setOnlineNodeNum(Integer onlineNodeNum) {
        this.onlineNodeNum = onlineNodeNum;
    }

    /**
     * 获取：控制器总数
     * 表字段：device_dmx.controller_num
     *
     * @return device_dmx.controller_num：控制器总数
     */
    public Integer getControllerNum() {
        return controllerNum;
    }

    /**
     * 设置：控制器总数
     * 表字段：device_dmx.controller_num
     *
     * @param controllerNum
     *            device_dmx.controller_num：控制器总数
     */
    public void setControllerNum(Integer controllerNum) {
        this.controllerNum = controllerNum;
    }

    /**
     * 获取：当前播放的节目ID
     * 表字段：device_dmx.program_config_id
     *
     * @return device_dmx.program_config_id：当前播放的节目ID
     */
    public Long getProgramConfigId() {
        return programConfigId;
    }

    /**
     * 设置：当前播放的节目ID
     * 表字段：device_dmx.program_config_id
     *
     * @param programConfigId
     *            device_dmx.program_config_id：当前播放的节目ID
     */
    public void setProgramConfigId(Long programConfigId) {
        this.programConfigId = programConfigId;
    }

    /**
     * 获取：宽度
     * 表字段：device_dmx.width
     *
     * @return device_dmx.width：宽度
     */
    public Integer getWidth() {
        return width;
    }

    /**
     * 设置：宽度
     * 表字段：device_dmx.width
     *
     * @param width
     *            device_dmx.width：宽度
     */
    public void setWidth(Integer width) {
        this.width = width;
    }

    /**
     * 获取：高度
     * 表字段：device_dmx.height
     *
     * @return device_dmx.height：高度
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * 设置：高度
     * 表字段：device_dmx.height
     *
     * @param height
     *            device_dmx.height：高度
     */
    public void setHeight(Integer height) {
        this.height = height;
    }
}